"""Rename content_data to content_json in PageContent

Revision ID: 07323e137424
Revises: fe1c23751aad
Create Date: 2025-09-11 17:46:03.824586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07323e137424'
down_revision = 'fe1c23751aad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_page_content', sa.Column('content_json', sa.JSON(), nullable=True))
    op.drop_column('website_page_content', 'content_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_page_content', sa.Column('content_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('website_page_content', 'content_json')
    # ### end Alembic commands ###
