"""Initial migration

Revision ID: 96d62e3e1be8
Revises: 
Create Date: 2025-09-11 10:54:51.741680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d62e3e1be8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('website_content_companyinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('linkedin', sa.String(length=200), nullable=True),
    sa.Column('twitter', sa.String(length=200), nullable=True),
    sa.Column('facebook', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('meta_title', sa.String(length=60), nullable=True),
    sa.Column('meta_description', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_companyinfo_id'), 'website_content_companyinfo', ['id'], unique=False)
    op.create_table('website_content_faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_faq_category'), 'website_content_faq', ['category'], unique=False)
    op.create_index(op.f('ix_website_content_faq_display_order'), 'website_content_faq', ['display_order'], unique=False)
    op.create_index(op.f('ix_website_content_faq_id'), 'website_content_faq', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_faq_is_active'), 'website_content_faq', ['is_active'], unique=False)
    op.create_index(op.f('ix_website_content_faq_question'), 'website_content_faq', ['question'], unique=False)
    op.create_table('website_content_serviceplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_monthly', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('monthly_savings', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_courses', sa.Integer(), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('api_requests_limit', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('color_primary', sa.String(length=7), nullable=True),
    sa.Column('color_secondary', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_serviceplan_display_order'), 'website_content_serviceplan', ['display_order'], unique=False)
    op.create_index(op.f('ix_website_content_serviceplan_id'), 'website_content_serviceplan', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_serviceplan_is_active'), 'website_content_serviceplan', ['is_active'], unique=False)
    op.create_index(op.f('ix_website_content_serviceplan_is_popular'), 'website_content_serviceplan', ['is_popular'], unique=False)
    op.create_index(op.f('ix_website_content_serviceplan_name'), 'website_content_serviceplan', ['name'], unique=False)
    op.create_index(op.f('ix_website_content_serviceplan_slug'), 'website_content_serviceplan', ['slug'], unique=True)
    op.create_table('website_content_testimonial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_position', sa.String(length=100), nullable=True),
    sa.Column('client_company', sa.String(length=150), nullable=True),
    sa.Column('client_photo', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_testimonial_display_order'), 'website_content_testimonial', ['display_order'], unique=False)
    op.create_index(op.f('ix_website_content_testimonial_id'), 'website_content_testimonial', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_testimonial_is_active'), 'website_content_testimonial', ['is_active'], unique=False)
    op.create_index(op.f('ix_website_content_testimonial_is_featured'), 'website_content_testimonial', ['is_featured'], unique=False)
    op.create_table('website_content_contactmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_contactmessage_id'), 'website_content_contactmessage', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_contactmessage_status'), 'website_content_contactmessage', ['status'], unique=False)
    op.create_table('website_content_newsarticle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.String(length=160), nullable=True),
    sa.Column('meta_keywords', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('featured_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_newsarticle_featured'), 'website_content_newsarticle', ['featured'], unique=False)
    op.create_index(op.f('ix_website_content_newsarticle_id'), 'website_content_newsarticle', ['id'], unique=False)
    op.create_index(op.f('ix_website_content_newsarticle_slug'), 'website_content_newsarticle', ['slug'], unique=True)
    op.create_index(op.f('ix_website_content_newsarticle_status'), 'website_content_newsarticle', ['status'], unique=False)
    op.create_index(op.f('ix_website_content_newsarticle_title'), 'website_content_newsarticle', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_content_newsarticle_title'), table_name='website_content_newsarticle')
    op.drop_index(op.f('ix_website_content_newsarticle_status'), table_name='website_content_newsarticle')
    op.drop_index(op.f('ix_website_content_newsarticle_slug'), table_name='website_content_newsarticle')
    op.drop_index(op.f('ix_website_content_newsarticle_id'), table_name='website_content_newsarticle')
    op.drop_index(op.f('ix_website_content_newsarticle_featured'), table_name='website_content_newsarticle')
    op.drop_table('website_content_newsarticle')
    op.drop_index(op.f('ix_website_content_contactmessage_status'), table_name='website_content_contactmessage')
    op.drop_index(op.f('ix_website_content_contactmessage_id'), table_name='website_content_contactmessage')
    op.drop_table('website_content_contactmessage')
    op.drop_index(op.f('ix_website_content_testimonial_is_featured'), table_name='website_content_testimonial')
    op.drop_index(op.f('ix_website_content_testimonial_is_active'), table_name='website_content_testimonial')
    op.drop_index(op.f('ix_website_content_testimonial_id'), table_name='website_content_testimonial')
    op.drop_index(op.f('ix_website_content_testimonial_display_order'), table_name='website_content_testimonial')
    op.drop_table('website_content_testimonial')
    op.drop_index(op.f('ix_website_content_serviceplan_slug'), table_name='website_content_serviceplan')
    op.drop_index(op.f('ix_website_content_serviceplan_name'), table_name='website_content_serviceplan')
    op.drop_index(op.f('ix_website_content_serviceplan_is_popular'), table_name='website_content_serviceplan')
    op.drop_index(op.f('ix_website_content_serviceplan_is_active'), table_name='website_content_serviceplan')
    op.drop_index(op.f('ix_website_content_serviceplan_id'), table_name='website_content_serviceplan')
    op.drop_index(op.f('ix_website_content_serviceplan_display_order'), table_name='website_content_serviceplan')
    op.drop_table('website_content_serviceplan')
    op.drop_index(op.f('ix_website_content_faq_question'), table_name='website_content_faq')
    op.drop_index(op.f('ix_website_content_faq_is_active'), table_name='website_content_faq')
    op.drop_index(op.f('ix_website_content_faq_id'), table_name='website_content_faq')
    op.drop_index(op.f('ix_website_content_faq_display_order'), table_name='website_content_faq')
    op.drop_index(op.f('ix_website_content_faq_category'), table_name='website_content_faq')
    op.drop_table('website_content_faq')
    op.drop_index(op.f('ix_website_content_companyinfo_id'), table_name='website_content_companyinfo')
    op.drop_table('website_content_companyinfo')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
