"""Add user custom permissions table

Revision ID: fe1c23751aad
Revises: b21ada072189
Create Date: 2025-09-11 16:06:39.585239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1c23751aad'
down_revision = 'b21ada072189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
