# Generated by Django 5.2.6 on 2025-09-10 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('tagline', models.CharField(max_length=255, verbose_name='Eslogan')),
                ('description', models.TextField(verbose_name='Descripción de la Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Logo')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='company/hero/', verbose_name='Imagen Principal')),
                ('meta_title', models.CharField(max_length=60, verbose_name='Título Meta')),
                ('meta_description', models.CharField(max_length=160, verbose_name='Descripción Meta')),
            ],
            options={
                'verbose_name': 'Información de la Empresa',
                'verbose_name_plural': 'Información de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('category', models.CharField(choices=[('general', 'General'), ('pricing', 'Precios'), ('technical', 'Técnico'), ('support', 'Soporte'), ('billing', 'Facturación')], default='general', max_length=50, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('views_count', models.IntegerField(default=0, verbose_name='Número de Vistas')),
                ('helpful_votes', models.IntegerField(default=0, verbose_name='Votos Útiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='URL Amigable')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Anual')),
                ('max_users', models.IntegerField(verbose_name='Máximo de Usuarios')),
                ('max_courses', models.IntegerField(verbose_name='Máximo de Cursos')),
                ('storage_gb', models.IntegerField(verbose_name='Almacenamiento (GB)')),
                ('api_requests_limit', models.IntegerField(verbose_name='Límite de Requests API')),
                ('features', models.JSONField(default=list, verbose_name='Características Incluidas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Plan Popular')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('color_primary', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color Primario')),
                ('color_secondary', models.CharField(default='#1E40AF', max_length=7, verbose_name='Color Secundario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Servicio',
                'verbose_name_plural': 'Planes de Servicio',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('client_position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('client_company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('content', models.TextField(verbose_name='Testimonio')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Calificación (1-5)')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/', verbose_name='Foto del Cliente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('in_progress', 'En Progreso'), ('responded', 'Respondido'), ('closed', 'Cerrado')], default='new', max_length=20, verbose_name='Estado')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respuesta del Admin')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL Amigable')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Resumen')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Imagen Destacada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Descripción')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Palabras Clave')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('views_count', models.IntegerField(default=0, verbose_name='Número de Vistas')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Artículo de Noticia',
                'verbose_name_plural': 'Artículos de Noticias',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
