# Generated by Django 5.2.6 on 2025-09-10 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('sevp_instance_url', models.URLField(verbose_name='URL de la Instancia SEVP')),
                ('sevp_database_name', models.CharField(max_length=100, verbose_name='Nombre de la Base de Datos')),
                ('sevp_api_token', models.CharField(max_length=255, verbose_name='Token de API SEVP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subscription_type', models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='basic', max_length=50, verbose_name='Tipo de Suscripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador Asignado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0, verbose_name='Total de Usuarios')),
                ('active_users', models.IntegerField(default=0, verbose_name='Usuarios Activos')),
                ('total_courses', models.IntegerField(default=0, verbose_name='Total de Cursos')),
                ('total_grades', models.IntegerField(default=0, verbose_name='Total de Calificaciones')),
                ('database_size_mb', models.FloatField(default=0, verbose_name='Tamaño de BD (MB)')),
                ('api_requests_count', models.IntegerField(default=0, verbose_name='Requests API')),
                ('response_time_avg', models.FloatField(default=0, verbose_name='Tiempo de Respuesta Promedio (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='clients.client')),
            ],
            options={
                'verbose_name': 'Estadística de Uso',
                'verbose_name_plural': 'Estadísticas de Uso',
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
