# Generated by Django 5.2.6 on 2025-09-10 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Versión')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='Rama de Git')),
                ('commit_hash', models.CharField(max_length=40, verbose_name='Hash del Commit')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('rolled_back', 'Revertido')], default='pending', max_length=20, verbose_name='Estado')),
                ('deployment_type', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Base de Datos'), ('full', 'Completo')], max_length=20, verbose_name='Tipo de Despliegue')),
                ('environment', models.CharField(choices=[('development', 'Desarrollo'), ('staging', 'Staging'), ('production', 'Producción')], default='production', max_length=20, verbose_name='Ambiente')),
                ('deployment_log', models.TextField(blank=True, verbose_name='Log de Despliegue')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('rollback_reason', models.TextField(blank=True, verbose_name='Razón del Rollback')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='clients.client')),
                ('deployed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Desplegado por')),
            ],
            options={
                'verbose_name': 'Despliegue',
                'verbose_name_plural': 'Despliegues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repository_url', models.URLField(verbose_name='URL del Repositorio Git')),
                ('default_branch', models.CharField(default='main', max_length=100, verbose_name='Rama por Defecto')),
                ('auto_deploy_enabled', models.BooleanField(default=False, verbose_name='Auto-Despliegue Habilitado')),
                ('auto_deploy_branch', models.CharField(default='main', max_length=100, verbose_name='Rama para Auto-Despliegue')),
                ('notify_on_success', models.BooleanField(default=True, verbose_name='Notificar en Éxito')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='Notificar en Fallo')),
                ('notification_emails', models.JSONField(default=list, verbose_name='Emails de Notificación')),
                ('auto_rollback_on_failure', models.BooleanField(default=False, verbose_name='Rollback Automático en Fallo')),
                ('max_failed_deployments', models.IntegerField(default=3, verbose_name='Máximo de Despliegues Fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_config', to='clients.client')),
            ],
            options={
                'verbose_name': 'Configuración de Despliegue',
                'verbose_name_plural': 'Configuraciones de Despliegue',
            },
        ),
        migrations.CreateModel(
            name='RollbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_version', models.CharField(max_length=50, verbose_name='Versión Anterior')),
                ('previous_commit_hash', models.CharField(max_length=40, verbose_name='Hash del Commit Anterior')),
                ('rollback_reason', models.TextField(verbose_name='Razón del Rollback')),
                ('rollback_successful', models.BooleanField(default=False, verbose_name='Rollback Exitoso')),
                ('rollback_started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rollback iniciado en')),
                ('rollback_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Rollback completado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_record', to='deployments.deployment')),
                ('rolled_back_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rollback realizado por')),
            ],
            options={
                'verbose_name': 'Registro de Rollback',
                'verbose_name_plural': 'Registros de Rollback',
            },
        ),
        migrations.CreateModel(
            name='DeploymentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100, verbose_name='Nombre del Paso')),
                ('step_order', models.IntegerField(verbose_name='Orden del Paso')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='pending', max_length=20, verbose_name='Estado')),
                ('step_log', models.TextField(blank=True, verbose_name='Log del Paso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='deployments.deployment')),
            ],
            options={
                'verbose_name': 'Paso de Despliegue',
                'verbose_name_plural': 'Pasos de Despliegue',
                'ordering': ['step_order'],
                'unique_together': {('deployment', 'step_order')},
            },
        ),
    ]
